### PR TITLE
Actors decode function

### PR DESCRIPTION
**Pull request by PierreAndreis**
There is no need to maintain a actors json when it's clearly how the actors are being sent.
In this case, we will maintain a bad tokens table

### CODE REVIEW

**Comment by PierreAndreis** [comment]
I don't know why the build is failing though

**Comment by seripap** [comment]
Can you remove then rebase anything that prepublish built? It'll be easier for me to see what's changed. Once I glance over the changes, i will merge and publish a new release with an updated dist.

**Comment by PierreAndreis** [comment]
What is the purpose of dist? I normally gitignore compiled files but wasn't sure about how it works on modules

**Comment by PierreAndreis** [comment]
It is still failling.. I will make a new PR

**Pull request closed without merging**
