### PR TITLE
Adding 5v5 game mode

### PR DESCRIPTION
**Pull request by PierreAndreis**

### CODE REVIEW

**Comment by PierreAndreis** [comment]
@seripap 5v5 should be dropping this week, we should get this released asap

**Comment by seripap** [comment]
Great. Also some interesting choice of `serverNames` on the MG side for this.

**Comment by seripap** [comment]
Released in `v1.3.7`, 35f6918

**Comment by PierreAndreis** [comment]
serverNames actually comes from SEMC. 

On a side note, I forgot to add the new items names. Will be doing that in a separated PR

**Pull request merged**
